name: Push Production to HuggingFace

on:
  push:
    branches: [main, retargeting]

  # run this workflow manualy from the Actions tab
  workflow_dispatch:

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          lfs: true
      - name: Deploy Production (main) to HuggingFace
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: git push --force https://faridkarimli:$HF_TOKEN@huggingface.co/spaces/edubotics/dl4ds_tutor main